name: build and deploy

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - uses: actions/checkout@v2

      # 检出emsdk
      - name: checkout emsdk
        uses: actions/checkout@v2
        with:
          repository: emscripten-core/emsdk
          path: emsdk
          submodules: recursive
          
      # 编译emsdk
      - name: build emsdk
        run: |
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest

      # 编译项目
      - name: build snake
        run: |
          source ./emsdk/emsdk_env.sh
          chmod +x build.sh
          ./build.sh

      # 上传
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: main
          folder: docs
